#!/bin/bash

#pwd
#export PKG_CONFIG_PATH=/home/jovyan/CyHunspell-1.2.1
#cd CyHunspell-1.2.1
#python ./setup.py install
conda install readline=6.2 --force --yes
conda install  -c conda-forge hunspell=2.0 --force --yes
