#!/bin/bash

source activate kernel

conda install readline=6.2 --force --yes

cd CyHunspell-1.2.1

python2 ./setup.py install

cp ./libs/unix/libhunspell-1.3.so.0 /srv/conda/envs/kernel/lib/libhunspell-1.3.so.0

cd ..
cp ./Hunspell_dict/dictionaries/*  /srv/conda/envs/kernel/lib/python2.7/site-packages/CyHunspell-1.2.1-py2.7-linux-x86_64.egg/dictionaries


source deactivate
